### PR TITLE
feat: Generate Runtypes

### PR DESCRIPTION
**Pull request by simenandre**
Adds [runtypes](https://github.com/pelotom/runtypes) to the mix!

/cc @ritz078

### CODE REVIEW

**Comment by hungneox** [comment]
It would be nice if we have this @ritz078

**Review by ritz078 — APPROVED** [review]
Thank you for your contribution 🎉

**Comment by ritz078** [comment]
@allcontributors please add @cobraz for code contribution.

**Comment by ritz078** [comment]
@allcontributors add @cobraz for code contribution

**Pull request merged**
